name: animated_custom_dropdown
description: Custom dropdown widget allows to add highly customizable dropdown widget in your projects. Features includes Search on list data, Network search, Multi-selection and many more.
version: 3.1.1
homepage: https://github.com/AbdullahChauhan/custom-dropdown

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

funding:
  - https://buymeacoffee.com/abdullahchauhan

screenshots:
  - description: "Custom dropdown Preview"
    path: screenshots/preview.png
  - description: "Dropdown example"
    path: screenshots/example_1.jpg
  - description: "Search dropdown example"
    path: screenshots/example_2.jpg
  - description: "Multi select dropdown example"
    path: screenshots/example_3.jpg

topics:
  - ui
  - dropdown
  - spinner
  - widget
  - widgets
